export const navigationData = [
  {
    id: 1,
    name: "Laptop",
    icon: "media/core/categories/2021/12/29/Rectangle 1461.png",
    color_hex: null,
    shared_url: "laptop",
    slug: "laptop",
    description:
      "Laptop là một thiết bị máy tính có kích thước nhỏ gọn và di động. Nó được thiết kế để sử dụng trong các hoạt động làm việc, giải trí hoặc học tập khi di chuyển mà không cần phải sử dụng những chiếc máy tính để bàn cồng kềnh.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-laptop.png",
  },
  {
    id: 7,
    name: "Bàn phím",
    icon: "media/core/categories/2024/1/24/ban-phim-xoa-nen-thinkpro.png",
    color_hex: null,
    shared_url: "ban-phim",
    slug: "ban-phim",
    description: "Bàn phím là một thiết bị đầu vào cho máy tính, được sử dụng để nhập dữ liệu và điều khiển các chức năng của máy tính. Bàn phím bao gồm một loạt các phím nhấn, các phím chữ, số, các ký tự đặc biệt và các phím chức năng để thực hiện các tác vụ.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-ban-phim.png",
    content: ""
  },
  {
    id: 27,
    name: "Âm thanh",
    icon: "media/core/categories/2024/1/24/thiet-ke-chua-co-ten-1-thinkpro.png",
    color_hex: null,
    shared_url: "am-thanh",
    slug: "am-thanh",
    description: "Âm thanh hay loa là một thiết bị điện tử được sử dụng để phát ra âm thanh. Nó bao gồm các thành phần khác như màng lọc tần số, bộ khuếch đại, điều khiển âm lượng,.. Loa có thể kết nối được với các thiết bị phát âm thanh thông qua dây cáp/kết nối không dây",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-am-thanh.png",
    content: ""
  },
  {
    id: 18,
    name: "Tai nghe",
    icon: "media/core/categories/2024/2/3/tai-nghe-thinkpro.png",
    color_hex: null,
    shared_url: "tai-nghe",
    slug: "tai-nghe",
    description: "Tai nghe là một trong những phụ kiện quan trọng, được sử dụng ngày càng rộng rãi ở thời điểm hiện tại. Thiết bị này có thể hỗ trợ người dùng đa chức năng, đa mục đích, điển hình nhất chính là nghe nhạc và đàm thoại.",
    parent_id: 27,
    thumbnail: "media/core/categories/2023/5/20/thumb-thinkpro-thinkpro-VHy.png",
    content: ""
  },
  {
    id: 49,
    name: "Loa",
    icon: "media/core/categories/2024/2/3/3-thinkpro.png",
    color_hex: null,
    shared_url: "loa",
    slug: "loa",
    description: "Loa là một thiết bị điện tử được sử dụng để phát ra âm thanh. Nó bao gồm các thành phần khác như màng lọc tần số, bộ khuếch đại, điều khiển âm lượng, ... Loa có thể kết nối được với các thiết bị phát âm thanh thông qua dây cáp hoặc kết nối không dây..",
    parent_id: 27,
    thumbnail: "media/core/categories/2023/5/20/thumb-thinkpro-thinkpro.png",
    content: ""
  },
  {
    id: 21,
    name: "Ghế công thái học",
    icon: "media/core/categories/2024/1/23/thiet-ke-chua-co-ten-thinkpro.png",
    color_hex: null,
    shared_url: "ghe-cong-thai-hoc",
    slug: "ghe-cong-thai-hoc",
    description: "Ghế công thái học là mẫu ghế được thiết kế với hình dáng và các tính năng đặc biệt, giúp giảm thiểu áp lực lên cơ thể, giảm đau lưng và cổ và giúp người sử dụng giữ được tư thế ngồi đúng để tránh những tổn thương do ngồi lâu.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-ghe-cong-thai-hoc-01.png",
    content: ""
  },
  {
    id: 54,
    name: "Bàn ghế trẻ em",
    icon: "media/core/categories/2024/1/10/ban-ghe-tre-em-thinkpro-zMY.png",
    color_hex: null,
    shared_url: "ban-ghe-tre-em",
    slug: "ban-ghe-tre-em",
    description: "Bàn ghế trẻ em đáp ứng những tiêu chuẩn khắt khe nhất cả về thiết kế cho tới chất lượng, sở hữu vẻ ngoài ấn tượng, đi kèm với những tính năng thông minh vượt trội như chống gù, chống cận; đây là một lựa chọn lý tưởng mà các bậc phụ huynh có thể lưu tâm",
    parent_id: null,
    thumbnail: "media/core/categories/2023/7/18/thumb-thinkpro-thinkpro.jpeg",
    content: ""
  },
  {
    id: 22,
    name: "Bàn nâng hạ",
    icon: "media/core/categories/2023/3/18/logo-ban-nang-ha-thinkpro-01.png",
    color_hex: null,
    shared_url: "ban-nang-ha",
    slug: "ban-nang-ha",
    description: "Bàn nâng hạ về cơ bản vẫn là bàn làm việc bình thường, tuy nhiên nó có cấu tạo đặc biệt ở hai chân bàn với các thanh khớp nối lồng vào nhau. Nhờ cấu trúc đặc biệt kết hợp động cơ nâng hạ được lồng vào chân bản giúp nó có thể thu các khớp nối vào để hạ ch",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-ban-nang-ha.png",
    content: ""
  },
  {
    id: 34,
    name: "Mặt bàn",
    icon: "media/core/categories/2024/1/9/0eb11f24-07fb-4ea6-853c-96fc40196575-thinkpro.png",
    color_hex: null,
    shared_url: "mat-ban",
    slug: "mat-ban",
    description: "Mặt bàn nâng hạ đa dạng về màu sắc và kích thước, được hoàn thiện bằng chất liệu bền bỉ, có thể sử dụng trong một thời gian dài. Bên cạnh đó, các góc cạnh của bàn được bo cong, đảm bảo an toàn tuyệt đối cho người sử dụng.",
    parent_id: 22,
    thumbnail: "media/core/categories/2023/5/22/thumb-thinkpro-thinkpro-cXK.png",
    content: ""
  },
  {
    id: 51,
    name: "Bộ bàn",
    icon: "media/core/categories/2023/5/22/bo-tron-2-vuong-vang-thinkpro.png",
    color_hex: null,
    shared_url: "bo-ban",
    slug: "bo-ban",
    description: "Bàn nâng hạ về cơ bản vẫn là bàn làm việc bình thường, tuy nhiên nó có cấu tạo đặc biệt ở hai chân bàn với các thanh khớp nối lồng vào nhau. Nhờ cấu trúc đặc biệt kết hợp động cơ nâng hạ được lồng vào chân bản giúp nó có thể thu các khớp nối.",
    parent_id: 22,
    thumbnail: "media/core/categories/2023/5/22/thumb-thinkpro-thinkpro.png",
    content: ""
  },
  {
    id: 52,
    name: "Khung bàn",
    icon: "media/core/categories/2023/5/22/khung-ban-nang-ha-cao-cap-fansi-thinkpro.png",
    color_hex: null,
    shared_url: "khung-ban",
    slug: "khung-ban",
    description: "Khung bàn nâng hạ với tính năng thay đổi chiều cao linh hoạt, dễ dàng điều chỉnh phù hợp theo dáng ngồi và tư thế của người dùng. Kết hợp với mặt bàn, sản phẩm hướng tới sự tiện nghi, tối giản cho góc làm việc và học tập..",
    parent_id: 22,
    thumbnail: "media/core/categories/2023/5/22/thumb-thinkpro-thinkpro-l1r.png",
    content: ""
  },
  {
    id: 20,
    name: "Thực tế ảo/ Game Console",
    icon: "media/core/categories/2024/2/25/ps5-slim-01-thinkpro.png",
    color_hex: null,
    shared_url: "may-choi-game",
    slug: "may-choi-game",
    description: "VR/ Game Console",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-may-choi-game.png",
    content: ""
  },
  {
    id: 43,
    name: "Máy chơi game/ Game Console",
    icon: "media/core/categories/2023/3/25/may-choi-game-va-thuc-te-ao-1.png",
    color_hex: null,
    shared_url: "may-game-thuc-te-ao",
    slug: "may-game-thuc-te-ao",
    description: "Máy chơi game là một thiết bị điện tử được thiết kế để chơi các trò chơi điện tử. Máy chơi game có thể được chia thành hai loại chính: máy chơi game cầm tay và máy chơi game để bàn",
    parent_id: 20,
    thumbnail: "media/core/categories/2023/3/25/may-choi-game-va-thuc-te-ao.jpeg",
    content: ""
  },
  {
    id: 44,
    name: "Phụ Kiện Game/VR",
    icon: "media/core/categories/2024/2/25/dualsense-ps5-15-thinkpro.png",
    color_hex: null,
    shared_url: "dia-game-phu-kien-game",
    slug: "dia-game-phu-kien-game",
    description: "Máy chơi game là một thiết bị điện tử được thiết kế để chơi các trò chơi điện tử. Máy chơi game có thể được chia thành hai loại chính: máy chơi game cầm tay và máy chơi game để bàn.",
    parent_id: 20,
    thumbnail: "media/core/categories/2023/3/25/dia-game.jpeg",
    content: ""
  },
  {
    id: 58,
    name: "Kính Thực Tế Ảo VR/AR",
    icon: "media/core/categories/2024/2/25/meta-quest-3-thinkpro-T7A.png",
    color_hex: null,
    shared_url: "thuc-te-ao-vrar",
    slug: "thuc-te-ao-vrar",
    description: "Thực tế ảo hay còn gọi là thực tại ảo (tiếng Anh là virtual reality, viết tắt là VR) là thuật ngữ miêu tả một môi trường được giả lập (ảo hóa) được tạo ra bởi con người nhờ vào các phần mềm chuyên dụng, và được điều khiển bởi một thiết bị thông minh",
    parent_id: 20,
    thumbnail: "media/core/categories/2024/2/25/meta-quest-3-thinkpro.png",
    content: ""
  },
  {
    id: 28,
    name: "Arm màn hình",
    icon: "media/core/categories/2022/3/15/arm-man-hinh-gia-tot-thinkpro.png",
    color_hex: null,
    shared_url: "arm-man-hinh",
    slug: "arm-man-hinh",
    description: "Arm màn hình là một “tay đỡ” để giữ màn hình máy tính ở vị trí mong muốn. Các loại Arm này thường được thiết kế giúp người dùng điều chỉnh độ cao, góc độ và khoảng cách giữa màn hình và mắt, nhằm tạo ra vị trí làm việc thoải mái và thuận tiện hơn.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-arm-man-hinh.png",
    content: ""
  },
  {
    id: 9,
    name: "Balo, Túi",
    icon: "media/core/categories/2024/1/24/balo-xoa-nen-thinkpro.png",
    color_hex: null,
    shared_url: "balo-tui",
    slug: "balo-tui",
    description: "Balo là sản phẩm thường được sử dụng để miêu tả một loại túi đeo vai hai quai và được sử dụng để đựng đồ khi đi học, đi du lịch hoặc đi làm. Túi xách là sản phẩm thường được sử dụng để đựng laptop, giúp người dùng có thể dễ dàng mang vác và bảo vệ máy tro",
    parent_id: null,
    thumbnail: "media/core/categories/2023/5/4/thumb-balo-tui-thinkpro.png",
    content: ""
  },
  {
    id: 47,
    name: "Túi",
    icon: "media/core/categories/2023/4/28/fit-black-1-thinkpro.png",
    color_hex: null,
    shared_url: "tui",
    slug: "tui",
    description: "Túi xách là sản phẩm thường được sử dụng để đựng laptop, giúp người dùng có thể dễ dàng mang vác, bảo vệ máy cũng như hạn chế tối đa  những tác động vật ký bên ngoài như trầy xước hoặc rơi vỡ.",
    parent_id: 9,
    thumbnail: "media/core/categories/2023/4/28/2-thinkpro.png",
    content: ""
  },
  {
    id: 48,
    name: "Balo",
    icon: "media/core/categories/2024/2/3/balo-thinkpro.png",
    color_hex: null,
    shared_url: "balo",
    slug: "balo",
    description: "Balo là sản phẩm thường được sử dụng để miêu tả một loại túi đeo vai hai quai và được sử dụng để đựng đồ khi đi học, đi du lịch hoặc đi làm.",
    parent_id: 9,
    thumbnail: "media/core/categories/2023/5/4/1-thinkpro.png",
    content: ""
  },
  {
    id: 8,
    name: "Chuột",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-2.png",
    color_hex: null,
    shared_url: "chuot",
    slug: "chuot",
    description: "Chuột máy tính một thiết bị ngoại vi được sử dụng để điều khiển con trỏ trên màn hình máy tính và thực hiện các thao tác trên giao diện đồ họa. Chuột thông thường được thiết kế nhỏ gọn, có hai, ba hoặc nhiều nút nhấn với bánh xe cuộn được đặt giữa hai nút",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-chuot.png",
    content: ""
  },
  {
    id: 19,
    name: "Màn hình",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-7.png",
    color_hex: null,
    shared_url: "man-hinh",
    slug: "man-hinh",
    description: "Màn hình máy tính (Computer display, Visual display unit hay Monitor) là thiết bị điện tử dùng để kết nối với máy tính nhằm mục đích hiển thị và phục vụ cho quá trình giao tiếp giữa người sử dụng với máy tính..",
    parent_id: null,
    thumbnail: "media/core/categories/2022/1/15/Màn hình PC.png",
    content: ""
  },
  {
    id: 11,
    name: "Cổng chuyển",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-8.png",
    color_hex: null,
    shared_url: "cong-chuyen",
    slug: "cong-chuyen",
    description: "Cổng chuyển (hay còn gọi là cổng kết nối) là một cổng truyền thông được sử dụng để chuyển đổi tín hiệu từ một loại giao diện sang một loại giao diện khác. Các cổng chuyển thường được sử dụng trong các thiết bị điện tử như máy tính, laptop, máy chiếu và cá",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-cong-chuyen.png",
    content: ""
  },
  {
    id: 13,
    name: "Phần mềm",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-14.png",
    color_hex: null,
    shared_url: "phan-mem",
    slug: "phan-mem",
    description: "Microsoft là một công ty sản xuất phần mềm lớn nhất thế giới, có trụ sở chính tại Mỹ. Các sản phẩm phần mềm của Microsoft bao gồm hệ điều hành Windows, các ứng dụng văn phòng như Microsoft Office (Word, Excel, PowerPoint, Outlook) và các sản phẩm khác như",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-phan-mem.png",
    content: ""
  },
  {
    id: 30,
    name: "Phụ kiện & Setup",
    icon: "media/core/categories/2023/3/30/phu-kien-va-setup-thinkpro.png",
    color_hex: null,
    shared_url: "phu-kien-va-setup",
    slug: "phu-kien-va-setup",
    description: "Phụ kiện & Setup bao gồm nhiều sản phẩm khác nhau, phục vụ đa nhu cầu của người dùng. Một số phụ kiện đáng chú ý như: kê tay bàn phím, ốp lưng, dán màn hình, phủ phím, ...",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/30/phu-kien-va-setup-thinkpro-2.png",
    content: ""
  },
  {
    id: 46,
    name: "Hộc tủ",
    icon: "media/core/categories/2022/12/14/AQUA_05.png",
    color_hex: null,
    shared_url: "hoc-tu",
    slug: "hoc-tu",
    description: "Hộc tủ tài liệu sẽ là người bạn đồng hành tiện dụng cho bất cứ ai và bất kỳ không gian sử dụng nào. Không đơn thuần chỉ có thiết kế đẹp, hộc tủ The Leaf còn mang tới hàng loạt những tính năng ưu việt như ổ khoá bảo mật, bánh xe di chuyển linh hoạt, ...",
    parent_id: null,
    thumbnail: "media/core/categories/2023/4/27/banner-noi-that-thinkpro-OLK.png",
    content: ""
  },
  {
    id: 56,
    name: "Robot Hút Bụi",
    icon: "media/core/categories/2024/1/10/robot-hut-bui-1-thinkpro-lwc.png",
    color_hex: null,
    shared_url: "robot-hut-bui",
    slug: "robot-hut-bui",
    description: "Robot hút bụi là một thiết bị tự động được thiết kế để làm sạch bề mặt sàn nhà mà không cần sự can thiệp của con người. Chúng thường được trang bị cảm biến để nhận diện vị trí và tránh va chạm, đồng thời có bộ lọc và bàn chải để loại bỏ bụi, rác và tóc. R",
    parent_id: null,
    thumbnail: "media/core/categories/2023/11/15/robot-hutbui111-thinkpro.png",
    content: ""
  }
];


export const promotionTabsData = [
  {
    id: 1,
    name: "Laptop",
    icon: "media/core/categories/2021/12/29/Rectangle 1461.png",
    color_hex: null,
    shared_url: "laptop",
    slug: "laptop",
    description:
      "Laptop là một thiết bị máy tính có kích thước nhỏ gọn và di động. Nó được thiết kế để sử dụng trong các hoạt động làm việc, giải trí hoặc học tập khi di chuyển mà không cần phải sử dụng những chiếc máy tính để bàn cồng kềnh.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-laptop.png",
  },
  {
    id: 7,
    name: "Bàn phím",
    icon: "media/core/categories/2024/1/24/ban-phim-xoa-nen-thinkpro.png",
    color_hex: null,
    shared_url: "ban-phim",
    slug: "ban-phim",
    description: "Bàn phím là một thiết bị đầu vào cho máy tính, được sử dụng để nhập dữ liệu và điều khiển các chức năng của máy tính. Bàn phím bao gồm một loạt các phím nhấn, các phím chữ, số, các ký tự đặc biệt và các phím chức năng để thực hiện các tác vụ.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-ban-phim.png",
    content: ""
  },
  {
    id: 18,
    name: "Tai nghe",
    icon: "media/core/categories/2024/2/3/tai-nghe-thinkpro.png",
    color_hex: null,
    shared_url: "tai-nghe",
    slug: "tai-nghe",
    description: "Tai nghe là một trong những phụ kiện quan trọng, được sử dụng ngày càng rộng rãi ở thời điểm hiện tại. Thiết bị này có thể hỗ trợ người dùng đa chức năng, đa mục đích, điển hình nhất chính là nghe nhạc và đàm thoại.",
    parent_id: 27,
    thumbnail: "media/core/categories/2023/5/20/thumb-thinkpro-thinkpro-VHy.png",
    content: ""
  },
  {
    id: 49,
    name: "Loa",
    icon: "media/core/categories/2024/2/3/3-thinkpro.png",
    color_hex: null,
    shared_url: "loa",
    slug: "loa",
    description: "Loa là một thiết bị điện tử được sử dụng để phát ra âm thanh. Nó bao gồm các thành phần khác như màng lọc tần số, bộ khuếch đại, điều khiển âm lượng, ... Loa có thể kết nối được với các thiết bị phát âm thanh thông qua dây cáp hoặc kết nối không dây..",
    parent_id: 27,
    thumbnail: "media/core/categories/2023/5/20/thumb-thinkpro-thinkpro.png",
    content: ""
  },
  {
    id: 21,
    name: "Ghế công thái học",
    icon: "media/core/categories/2024/1/23/thiet-ke-chua-co-ten-thinkpro.png",
    color_hex: null,
    shared_url: "ghe-cong-thai-hoc",
    slug: "ghe-cong-thai-hoc",
    description: "Ghế công thái học là mẫu ghế được thiết kế với hình dáng và các tính năng đặc biệt, giúp giảm thiểu áp lực lên cơ thể, giảm đau lưng và cổ và giúp người sử dụng giữ được tư thế ngồi đúng để tránh những tổn thương do ngồi lâu.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-ghe-cong-thai-hoc-01.png",
    content: ""
  },
  {
    id: 54,
    name: "Bàn ghế trẻ em",
    icon: "media/core/categories/2024/1/10/ban-ghe-tre-em-thinkpro-zMY.png",
    color_hex: null,
    shared_url: "ban-ghe-tre-em",
    slug: "ban-ghe-tre-em",
    description: "Bàn ghế trẻ em đáp ứng những tiêu chuẩn khắt khe nhất cả về thiết kế cho tới chất lượng, sở hữu vẻ ngoài ấn tượng, đi kèm với những tính năng thông minh vượt trội như chống gù, chống cận; đây là một lựa chọn lý tưởng mà các bậc phụ huynh có thể lưu tâm",
    parent_id: null,
    thumbnail: "media/core/categories/2023/7/18/thumb-thinkpro-thinkpro.jpeg",
    content: ""
  },
  {
    id: 34,
    name: "Mặt bàn",
    icon: "media/core/categories/2024/1/9/0eb11f24-07fb-4ea6-853c-96fc40196575-thinkpro.png",
    color_hex: null,
    shared_url: "mat-ban",
    slug: "mat-ban",
    description: "Mặt bàn nâng hạ đa dạng về màu sắc và kích thước, được hoàn thiện bằng chất liệu bền bỉ, có thể sử dụng trong một thời gian dài. Bên cạnh đó, các góc cạnh của bàn được bo cong, đảm bảo an toàn tuyệt đối cho người sử dụng.",
    parent_id: 22,
    thumbnail: "media/core/categories/2023/5/22/thumb-thinkpro-thinkpro-cXK.png",
    content: ""
  },
  {
    id: 51,
    name: "Bộ bàn",
    icon: "media/core/categories/2023/5/22/bo-tron-2-vuong-vang-thinkpro.png",
    color_hex: null,
    shared_url: "bo-ban",
    slug: "bo-ban",
    description: "Bàn nâng hạ về cơ bản vẫn là bàn làm việc bình thường, tuy nhiên nó có cấu tạo đặc biệt ở hai chân bàn với các thanh khớp nối lồng vào nhau. Nhờ cấu trúc đặc biệt kết hợp động cơ nâng hạ được lồng vào chân bản giúp nó có thể thu các khớp nối.",
    parent_id: 22,
    thumbnail: "media/core/categories/2023/5/22/thumb-thinkpro-thinkpro.png",
    content: ""
  },
  {
    id: 52,
    name: "Khung bàn",
    icon: "media/core/categories/2023/5/22/khung-ban-nang-ha-cao-cap-fansi-thinkpro.png",
    color_hex: null,
    shared_url: "khung-ban",
    slug: "khung-ban",
    description: "Khung bàn nâng hạ với tính năng thay đổi chiều cao linh hoạt, dễ dàng điều chỉnh phù hợp theo dáng ngồi và tư thế của người dùng. Kết hợp với mặt bàn, sản phẩm hướng tới sự tiện nghi, tối giản cho góc làm việc và học tập..",
    parent_id: 22,
    thumbnail: "media/core/categories/2023/5/22/thumb-thinkpro-thinkpro-l1r.png",
    content: ""
  },
  {
    id: 43,
    name: "Máy chơi game/ Game Console",
    icon: "media/core/categories/2023/3/25/may-choi-game-va-thuc-te-ao-1.png",
    color_hex: null,
    shared_url: "may-game-thuc-te-ao",
    slug: "may-game-thuc-te-ao",
    description: "Máy chơi game là một thiết bị điện tử được thiết kế để chơi các trò chơi điện tử. Máy chơi game có thể được chia thành hai loại chính: máy chơi game cầm tay và máy chơi game để bàn",
    parent_id: 20,
    thumbnail: "media/core/categories/2023/3/25/may-choi-game-va-thuc-te-ao.jpeg",
    content: ""
  },
  {
    id: 44,
    name: "Phụ Kiện Game/VR",
    icon: "media/core/categories/2024/2/25/dualsense-ps5-15-thinkpro.png",
    color_hex: null,
    shared_url: "dia-game-phu-kien-game",
    slug: "dia-game-phu-kien-game",
    description: "Máy chơi game là một thiết bị điện tử được thiết kế để chơi các trò chơi điện tử. Máy chơi game có thể được chia thành hai loại chính: máy chơi game cầm tay và máy chơi game để bàn.",
    parent_id: 20,
    thumbnail: "media/core/categories/2023/3/25/dia-game.jpeg",
    content: ""
  },
  {
    id: 58,
    name: "Kính Thực Tế Ảo VR/AR",
    icon: "media/core/categories/2024/2/25/meta-quest-3-thinkpro-T7A.png",
    color_hex: null,
    shared_url: "thuc-te-ao-vrar",
    slug: "thuc-te-ao-vrar",
    description: "Thực tế ảo hay còn gọi là thực tại ảo (tiếng Anh là virtual reality, viết tắt là VR) là thuật ngữ miêu tả một môi trường được giả lập (ảo hóa) được tạo ra bởi con người nhờ vào các phần mềm chuyên dụng, và được điều khiển bởi một thiết bị thông minh",
    parent_id: 20,
    thumbnail: "media/core/categories/2024/2/25/meta-quest-3-thinkpro.png",
    content: ""
  },
  {
    id: 28,
    name: "Arm màn hình",
    icon: "media/core/categories/2022/3/15/arm-man-hinh-gia-tot-thinkpro.png",
    color_hex: null,
    shared_url: "arm-man-hinh",
    slug: "arm-man-hinh",
    description: "Arm màn hình là một “tay đỡ” để giữ màn hình máy tính ở vị trí mong muốn. Các loại Arm này thường được thiết kế giúp người dùng điều chỉnh độ cao, góc độ và khoảng cách giữa màn hình và mắt, nhằm tạo ra vị trí làm việc thoải mái và thuận tiện hơn.",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-arm-man-hinh.png",
    content: ""
  },
  {
    id: 47,
    name: "Túi",
    icon: "media/core/categories/2023/4/28/fit-black-1-thinkpro.png",
    color_hex: null,
    shared_url: "tui",
    slug: "tui",
    description: "Túi xách là sản phẩm thường được sử dụng để đựng laptop, giúp người dùng có thể dễ dàng mang vác, bảo vệ máy cũng như hạn chế tối đa  những tác động vật ký bên ngoài như trầy xước hoặc rơi vỡ.",
    parent_id: 9,
    thumbnail: "media/core/categories/2023/4/28/2-thinkpro.png",
    content: ""
  },
  {
    id: 48,
    name: "Balo",
    icon: "media/core/categories/2024/2/3/balo-thinkpro.png",
    color_hex: null,
    shared_url: "balo",
    slug: "balo",
    description: "Balo là sản phẩm thường được sử dụng để miêu tả một loại túi đeo vai hai quai và được sử dụng để đựng đồ khi đi học, đi du lịch hoặc đi làm.",
    parent_id: 9,
    thumbnail: "media/core/categories/2023/5/4/1-thinkpro.png",
    content: ""
  },
  {
    id: 8,
    name: "Chuột",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-2.png",
    color_hex: null,
    shared_url: "chuot",
    slug: "chuot",
    description: "Chuột máy tính một thiết bị ngoại vi được sử dụng để điều khiển con trỏ trên màn hình máy tính và thực hiện các thao tác trên giao diện đồ họa. Chuột thông thường được thiết kế nhỏ gọn, có hai, ba hoặc nhiều nút nhấn với bánh xe cuộn được đặt giữa hai nút",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-chuot.png",
    content: ""
  },
  {
    id: 19,
    name: "Màn hình",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-7.png",
    color_hex: null,
    shared_url: "man-hinh",
    slug: "man-hinh",
    description: "Màn hình máy tính (Computer display, Visual display unit hay Monitor) là thiết bị điện tử dùng để kết nối với máy tính nhằm mục đích hiển thị và phục vụ cho quá trình giao tiếp giữa người sử dụng với máy tính..",
    parent_id: null,
    thumbnail: "media/core/categories/2022/1/15/Màn hình PC.png",
    content: ""
  },
  {
    id: 11,
    name: "Cổng chuyển",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-8.png",
    color_hex: null,
    shared_url: "cong-chuyen",
    slug: "cong-chuyen",
    description: "Cổng chuyển (hay còn gọi là cổng kết nối) là một cổng truyền thông được sử dụng để chuyển đổi tín hiệu từ một loại giao diện sang một loại giao diện khác. Các cổng chuyển thường được sử dụng trong các thiết bị điện tử như máy tính, laptop, máy chiếu và cá",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-cong-chuyen.png",
    content: ""
  },
  {
    id: 13,
    name: "Phần mềm",
    icon: "media/core/categories/2021/12/29/Rectangle 1461-14.png",
    color_hex: null,
    shared_url: "phan-mem",
    slug: "phan-mem",
    description: "Microsoft là một công ty sản xuất phần mềm lớn nhất thế giới, có trụ sở chính tại Mỹ. Các sản phẩm phần mềm của Microsoft bao gồm hệ điều hành Windows, các ứng dụng văn phòng như Microsoft Office (Word, Excel, PowerPoint, Outlook) và các sản phẩm khác như",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/17/thumb-phan-mem.png",
    content: ""
  },
  {
    id: 30,
    name: "Phụ kiện & Setup",
    icon: "media/core/categories/2023/3/30/phu-kien-va-setup-thinkpro.png",
    color_hex: null,
    shared_url: "phu-kien-va-setup",
    slug: "phu-kien-va-setup",
    description: "Phụ kiện & Setup bao gồm nhiều sản phẩm khác nhau, phục vụ đa nhu cầu của người dùng. Một số phụ kiện đáng chú ý như: kê tay bàn phím, ốp lưng, dán màn hình, phủ phím, ...",
    parent_id: null,
    thumbnail: "media/core/categories/2023/3/30/phu-kien-va-setup-thinkpro-2.png",
    content: ""
  },
  {
    id: 46,
    name: "Hộc tủ",
    icon: "media/core/categories/2022/12/14/AQUA_05.png",
    color_hex: null,
    shared_url: "hoc-tu",
    slug: "hoc-tu",
    description: "Hộc tủ tài liệu sẽ là người bạn đồng hành tiện dụng cho bất cứ ai và bất kỳ không gian sử dụng nào. Không đơn thuần chỉ có thiết kế đẹp, hộc tủ The Leaf còn mang tới hàng loạt những tính năng ưu việt như ổ khoá bảo mật, bánh xe di chuyển linh hoạt, ...",
    parent_id: null,
    thumbnail: "media/core/categories/2023/4/27/banner-noi-that-thinkpro-OLK.png",
    content: ""
  },
  {
    id: 56,
    name: "Robot Hút Bụi",
    icon: "media/core/categories/2024/1/10/robot-hut-bui-1-thinkpro-lwc.png",
    color_hex: null,
    shared_url: "robot-hut-bui",
    slug: "robot-hut-bui",
    description: "Robot hút bụi là một thiết bị tự động được thiết kế để làm sạch bề mặt sàn nhà mà không cần sự can thiệp của con người. Chúng thường được trang bị cảm biến để nhận diện vị trí và tránh va chạm, đồng thời có bộ lọc và bàn chải để loại bỏ bụi, rác và tóc. R",
    parent_id: null,
    thumbnail: "media/core/categories/2023/11/15/robot-hutbui111-thinkpro.png",
    content: ""
  }
];
